module.exports = {
  extends: ['airbnb'],
  plugins: ['react', 'react-hooks', 'react-native', 'prettier'],
  parserOptions: {
    ecmaVersion: 2020,
  },
  rules: {
    'prettier/prettier': [
      'error',
      {
        singleQuote: true,
        semi: true,
        useTabs: false,
        trailingComma: 'all',
        arrowParen: 'avoid',
      },
    ],
    'import/no-dynamic-require': 'off',
    'import/no-extraneous-dependencies': 'off',
    'import/prefer-default-export': 'off',
    'react/destructuring-assignment': 'off',
    'react/jsx-boolean-value': 'off',
    'react/jsx-curly-newline': 'off',
    'react/jsx-filename-extension': 'off',
    'react/jsx-no-bind': 'error',
    'react/jsx-one-expression-per-line': 'off',
    'react/jsx-props-no-spreading': 'off',
    'react/jsx-wrap-multilines': 'off',
    'react/no-unused-prop-types': 'off',
    'react/no-unused-state': 'off',
    'react/prefer-stateless-function': [
      'off',
      {
        ignorePureComponents: true,
      },
    ],
    'react/prop-types': 'off',
    'react/require-default-props': 'off',
    'react-hooks/exhaustive-deps': 'off',
    'react-hooks/rules-of-hooks': 'error',
    'jsx-a11y/click-events-have-key-events': 'off',
    'jsx-a11y/html-has-lang': 'off',
    'jsx-a11y/no-noninteractive-element-interactions': 'off',
    'jsx-a11y/no-static-element-interactions': 'off',
    'react-native/no-inline-styles': 'warn',
    'react-native/no-single-element-style-arrays': 'warn',
    'react-native/no-unused-styles': 'warn',
    'arrow-body-style': 'off',
    'arrow-parens': ['error', 'as-needed'],
    'camelcase': 'off',
    'comma-dangle': 'off',
    'consistent-return': 'off',
    'function-paren-newline': 'off',
    'generator-star-spacing': [
      'error',
      {
        before: false,
        after: true,
        anonymous: { before: false, after: true },
        method: { before: false, after: true },
      },
    ],
    'global-require': 'off',
    'implicit-arrow-linebreak': 'off',
    'indent': 'off',
    'no-case-declarations': 'off',
    'no-confusing-arrow': 'off',
    'no-console': 'off',
    'no-extra-boolean-cast': 'off',
    'no-fallthrough': 'off',
    'no-nested-ternary': 'off',
    'no-param-reassign': 'off',
    'no-underscore-dangle': 'off',
    'no-unused-vars': 'warn',
    'no-use-before-define': 'off',
    'no-useless-escape': 'off',
    'object-curly-newline': 'off',
    'operator-linebreak': 'off',
    'prefer-destructuring': 'warn',
  },
};
